export const categoryConstants = {
    ADD_REQUEST: 'ADD_CATEGORY',
    ADD_SUCCESS: 'ADD_CATEGORY_SUCCESS',
    ADD_FAILURE: 'ADD_CATEGORY_FAILURE',

    GET_REQUEST: 'GET_CATEGORY',
    GET_SUCCESS: 'GET_CATEGORY_SUCCESS',
    GET_FAILURE: 'GET_CATEGORY_FAILURE',


};
