export const HomeConstants = {
    OPEN_LOGIN_MODAL: 'OPEN_LOGIN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    LOGIN_VIEW: 'LOGIN_VIEW',
    OPEN_SIGNUP_MODAL: 'OPEN_SIGNUP_MODAL',
    COUNTER_CLICK:'COUNTER_CLICK',
};
