export const miscConstants = {
    OPEN_SPINNER: 'OPEN_SPINNER',
    CLOSE_SPINNER: 'CLOSE_SPINNER',
    OPEN_CATEGORY_MODAL: 'OPEN_CATEGORY_MODAL',
    CLOSE_CATEGORY_MODAL: 'CLOSE_CATEGORY_MODAL',
};
